### ISSUE TITLE
StatHistorianReportGenerator intermittent crash

### ISSUE THREAD

**Issue by StephenCWills** [GridProtectionAlliance/gsf#9]
Very rarely, it's been noted that the automatic report generation fails with the following error.

```
Source:        .NET Runtime
Application: StatHistorianReportGenerator.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
  at GSF.Historian.Files.TimeSortedArchiveFileScanner.GetScanners()
  at GSF.Historian.Files.TimeSortedArchiveFileScanner+<Read>d__24.MoveNext()
  at GSF.Historian.Files.ArchiveFile+<ReadData>d__256.MoveNext()
  at StatHistorianReportGenerator.CompletenessReportGenerator.ReadStatistics()
  at StatHistorianReportGenerator.CompletenessReportGenerator.GenerateReport()
  at StatHistorianReportGenerator.Program.GenerateCompletenessReport()
  at StatHistorianReportGenerator.Program.Main()
```

**Comment by StephenCWills** [comment]
If the user attempts to manually generate the report that failed, it's very likely that the report generation will succeed. Therefore, this does not appear to be a problem with historian corruption, but rather is more likely some sort of synchronization issue between the historian writer and historian reader.

**Comment by StephenCWills** [comment]
Just checked in a fix that very likely solves this issue: https://github.com/GridProtectionAlliance/gsf/commit/46cdc6dc9ebb2e3f36c74fe533f870f9c365f747
